version: '3.9'

services:
  pg:
    container_name: pg
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
    ports:
      - '5432:5432'
    volumes:
      - dev:/var/lib/postgresql/data
    networks:
      - webnet
    restart: always
volumes:
  dev: {}
networks:
  webnet:
